### ISSUE TITLE
revamp docs

### ISSUE THREAD

**Issue by nrdxp** [divnix/digga#111]
We need a more thorough mechanism for documentation covering the following bases:
- [ ] all library functions
- [ ] profile blurbs
- [x] repo layout description
- [x] flk command
- [ ] user blurbs
- [ ] common examples of various actions
- [ ] various integration docs
  - [x] deploy-rs
  - [ ] NUR
  - [ ] devshell

Tracking #113

**Comment by Pacman99** [comment]
Maybe a README in each folder that documents the purpose of the code in it and how to use it. It would be obvious for new users learning, and easy for contributors to keep updated.
