### ISSUE TITLE
Can't override nixpkgs sub-systems with deprecated attributes

### ISSUE THREAD

**Issue by Pacman99** [divnix/digga#13]
## Expected Behavior
It should be possible to override gnome or other subsystems like this:
```
gnome = prev.gnome // { ... };
```
## Current Behavior
This throws an error because `flattenTree` then ends up trying to evaluate the entire namespace and that cause things like `gnome.corePackages` to throw errors.

## Possible Solution
`filterPackages` before `flattenTree`. This means users can't define custom namespaces.

## Steps to Reproduce

1. Override gnome, example: https://cloud.tissot.de/gitea/benneti/nixos/src/branch/broken/overlays/nautilus-python.nix
2. You will get an error like this: https://github.com/divnix/devos/issues/283#issuecomment-842140516
3.
4.

## Context
It is really important to be able to override sub-systems. And many of them have attributes that throw errors. We need to figure out a way to include the sub-system without evaluating all of it.

The problematic code: https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/staging/src/fromOverlays.nix

## Your Environment
A nixos config that was reported to trigger this: https://cloud.tissot.de/gitea/benneti/nixos/src/branch/broken

cc @benneti

**Comment by blaggacao** [comment]
@Pacman99 do you know wich line of the offensive code is precisely triggering the error? I can work back my understanding of the issue from there.

**Comment by Pacman99** [comment]
This should fix it from flake-util's side: https://github.com/numtide/flake-utils/pull/34

**Comment by Pacman99** [comment]
But there is something else to consider: Do we want to export all packages from sub-systems that are overriden?

In the example shown, a `nix flake show` would reveal that every package in gnome is now going to be exported. You could use a `__dontExport` to get around it. But I feel like this situation could be improved somehow.

**Comment by blaggacao** [comment]
The issue with exporting those overrides as packages is that they hardly satisfy the novelty requirement that would justify that export, right?

Some overrides might be sufficiently useful as an overlay, though?

I think this is going to be a cut-off threshold on which we have to make a trade-off-dominated decision.

So we won't be able to satisfy every single need appropriately.

I think, we can start suggesting to work with `__dontExport`, and transfer that trade-off decision to the user.

On the other hand, defaulting to exporting those might just result in huge amounts of non-novelty stuff cluttering the bazar of ideas.

**Comment by Pacman99** [comment]
> On the other hand, defaulting to exporting those might just result in huge amounts of non-novelty stuff cluttering the bazar of ideas.

I think this is the more important point. I agree on cut-offs, but also defaults are really powerful. Maybe package sub-systems should be opt-in somehow?

**Comment by Pacman99** [comment]
I believe this could be done in `fromOverlays`/`packagesFromOverlaysBuilderConstructor`.

So API would be like so:
 - all top-level packages are exported unless overlay has `__dontExport` set.
 - package subsystems are not exported unless subsystem has `__dontExport = false;` set.

**Comment by Pacman99** [comment]
Implementation in flake-utils-plus: https://github.com/gytis-ivaskevicius/flake-utils-plus/pull/57

This fix will only make into the next release of digga. So if your running into this problem right now you can just set `__dontExport` in any overlay that overrides a sub-system(gnome, python.pkgs, ...). Or switch your `digga` input to the develop branch when the fix makes it in there. I recommend the former option for stability.

**Comment by Pacman99** [comment]
Going to close this based off of fromOverlays no longer exporting entire sub-systems.
