### ISSUE TITLE
Docker builds stopped working after update

### ISSUE THREAD

**Issue by codygman** [divnix/digga#209]
##### This is beeing tracked by https://github.com/NixOS/nixpkgs/issues/36214#issuecomment-860249879 (and closed once resolved) (edit @blaggacao)

---

This might not even belong here, but in the off chance that rebuilds or reactivation don't fully work correctly and devos does anything special I'm posting it in case.

I updated my dependencies here:

https://github.com/codygman/devos/commit/eedf122338f560822b39d0104eb067f461518ba6

I went to build a docker container I'd built recently got a failure, so I tried getting a shell in the base container and calling the failing command:

```
❯ docker run -it docker:19.03.13
/ # apk add --no-cache entr git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  entr (missing):
    required by: world[entr]
  git (missing):
    required by: world[git]
```

After a `flk work-tower switch` at [this commit](https://github.com/codygman/devos/commit/fdf025796d6861f00380da4ad5b1a5946d87c411) I tried the above again and got the issue.

Upon rebooting though and still at that commit, this happens:

```
❯ docker run -it docker:19.03.13
/ # apk add --no-cache entr git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/6) Installing entr (4.5-r0)
(2/6) Installing nghttp2-libs (1.41.0-r0)
(3/6) Installing libcurl (7.69.1-r3)
(4/6) Installing expat (2.2.9-r1)
(5/6) Installing pcre2 (10.35-r0)
(6/6) Installing git (2.26.3-r0)
Executing busybox-1.31.1-r19.trigger
OK: 27 MiB in 26 packages
```

It works.

I wouldn't be surprised if maybe this is an issue similar to [this one about socket activation](https://github.com/NixOS/nixpkgs/issues/11478#issuecomment-183880642) and the correct course of action being creating an issue upstream.

**Comment by codygman** [comment]
I'm not sure if devos wants to guarantee sane defaults for something like docker or not, but I also ran into "too many files open" and ended up finding this yet to be merged PR that addresses that issue:

https://github.com/NixOS/nixpkgs/pull/112472

I think devos relies on nixpkgs to set these defaults unless it's something egregious? Actually, I don't know if core even has docker anymore or if it's a goal for community to have sane defaults.

**Comment by blaggacao** [comment]
> I think devos relies on nixpkgs to set these defaults unless it's something egregious? Actually, I don't know if core even has docker anymore or if it's a goal for community to have sane defaults.

I don't think it is a bad idea to preempt those changes in the `community` branch.

In the case those are specific PRs from upstream that we might want to pull in to make devos generally more usable, we should probably defer to https://github.com/NixOS/nix/issues/3920?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEwNjQxNDQ4NTg6NzU0ODI5NQ%3D%3D#issuecomment-806622462

**Comment by nrdxp** [comment]
Docker is obviously huge for hackers of all stripes, so ensuring simple usage is certainly a good idea in general. Perhaps a nice test suite to ensure docker is working correctly would be in order, to ensure PRs don't break it.

**Comment by blaggacao** [comment]
Let's close this once https://github.com/NixOS/nixpkgs/pull/112472 is merged.

**Comment by blaggacao** [comment]
Fix: https://github.com/NixOS/nixpkgs/pull/126777
