### ISSUE TITLE
Add option of devshellOverlays for devshell

### ISSUE THREAD

**Issue by GTrunSec** [divnix/digga#21]
This issue-based on https://github.com/divnix/digga/pull/11/commits/88e55af866ae2916b6fbdb120262be2783f8fe9a
Sometimes, I would like to use some packages from overlay to deveshell packages.  So, I added this option here.
https://github.com/GTrunSec/digga/commit/d93852269b0e32ed00b0dd1c721c7c2fa7574b96

Exp:
```
   devshellModules = [ ./devshell.toml ];
   devshellOverlays = [ sops-nix.overlay ];                                                                       
   #devShellOverlays= shareOverlays;
```

**Comment by blaggacao** [comment]
This makes sense.


We can work around it by not using `devshell.toml` but a more flexible `devshell.nix` and import that passing along `self.pkgs`.

On the other hand, I have to say, `devshellOverlays` is just quite convenient.

And if overlays is all one needs, we can stick with the (simpler) toml format.

we might consider, though:

```
devshell = { modules = []; overlays = [];};
```

**Comment by GTrunSec** [comment]
>devshell = { modules = []; overlays = [];};
+1, That would be good one.

**Comment by Pacman99** [comment]
I'm a little confused about this request. Any overlay added to your default channel(nixos) is added to the `pkgs` that your devshell is built on.
What is the goal for devshellOverlays?

I'm thinking:
```
devshell = { modules = []; overlays = []; externalModules = [ ]; };
```

**Comment by Pacman99** [comment]
I believe this would achieve the same thing:
```
channels.nixos = {
  overlays = [ sops-nix.overlay ];
}
```
and sops-nix should be in "part of" your devshell - as in not installed but available.

If that doesn't happen, then we should fix that.

**Comment by Pacman99** [comment]
To prevent the additional API argument I would prefer #22, but let me know if I'm missing a good warrant for `devshell.overlays`.

**Comment by blaggacao** [comment]
I had to look this up again:

The current devshell consumes `nixpkgs`, the only way to conform this to `nixos` is by using `digga.inputs.nixpkgs.follows`. But still, overlays of `nixos` are not applied.

We did this for the following reasons:

- the `digga` lib by itself depends on nixpkgs for some things. In that sense it's not a pure lib.
- those things have either to do with tests or with devshell.
- we agreed on nixpkgs dependency on the digga level for only tests / devshell

I think we would want to uphold that conceptual separation by continuing to using nixpkgs.

On the other hand, a default channel is host specific configuration within the `hosts` namespace. I am a bit wary that it would be legit to semantically reuse it in another namespace (`devshell`).

Therefore, I think creating a `devshell` namespace is the most normalized form of implementing this. We might analyze though, if we have similar needs for tests:

When oberserving the maxime of dev/ci parity, it should always be possible that devshell is a wrapper around the ci, tests environment. That is any devshell overlays should be a superset of those eventually used for tests. Note, that tests currently only use `pkgs.lib` and build-support which is essentially lib-like, as well, no "real" dep on a package.

Hence, I think it is ok to reuse the devshell namespace for the pkgs that also gets supplied to tests, and in general to the entire `pkgs-lib`.

**Comment by Pacman99** [comment]
We already use the "default channel" for tests and shell. All I want to do in #22 is just preserve the overlays for that channel.

I disagree on separating the idea of a "default channel" between hosts and devshell. Then we would have to re-implement the concept of `channels` within devshell. `channels` are a global thing that should be used across digga.

Currently we pick the default channel by looking at `hostDefaults.channelName` which makes a lot of sense since channels used for hosts would be the channels you would likely want for your devshell. I would prefer to encourage the concept of the default channel across digga.

Now we could change that by adding a top-level `defaultChannel` argument. But I would like the "default channel" to be a concept preserved across hosts and devshell. Splitting it up is confusing for a user and in implementation.

**Comment by Pacman99** [comment]
Also `devshell.overlays` is anyways going to be applied to the default channel in any version of its implementation. The only way to prevent that is to re-create a channels concept for devshell.

**Comment by blaggacao** [comment]
I looked at rhe wrong code. :smile:

Look and feel of https://github.com/divnix/digga/blob/5ef9b8cabbc10c9b4fe5534107224c7241c63b3d/src/mkFlake/default.nix#L90

is good.

The distinction to digga standalone use is made in the way pkgs-lib get's `pkgs` in  flake.nix vs how it's invoked in `mkFlake`.

**Comment by GTrunSec** [comment]
Thanks so much, the `append overlay` has been solved my problem.
