### ISSUE TITLE
Helper for vimPlugins, vscode-extensions, etc 

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [divnix/digga#321]
## Would your feature fix an existing issue?

No but it would make it even easier to get running with nixos. 

## Describe the solution you'd like

I'm not sure what the best version of this idea looks like but I was thinking a flake in `pkgs/vimPlugins` that takes every input and turns it into a pkgs.vimPlugins package and something similar vscode-extensions. 

Maybe even something more generic like where `pkgs/sets/${pkgSet}/flake.nix` takes all inputs and turn them into `pkgs.${pkgSet}.input`

so this

```nix
# pkgs/sets/vimPlugins/flake.nix

{
  description = "Vim Plugin Sources";

  inputs = {
    vim-cargo-make = {
      url = "github:nastevens/vim-cargo-make";
      flake = false;
    };

}
```

creates

```nix
pkgs.vimPlugins.vim-cargo-make
```

## Additional context

I think for developers this would be quite convenient.

**Comment by nrdxp** [comment]
Interesting idea. Actually, I tried to modify the upstream [script](https://github.com/NixOS/nixpkgs/pull/118109), to make packaging these plugins a lot simpler, but it didn't seem to garner much favour. I kinda let it go stale (not intentionally) as I've been hammered with work stuff. 

Maybe DevOS is a better target for this kinda of thing after all.

**Comment by blaggacao** [comment]
```toml
description = "Vim Plugin Sources"
[inputs]
vim-cargo-make.url = "github:nastevens/vim-cargo-make"
```

see also: https://github.com/divnix/devos/blob/62f09e12627e884e4a15e9668d07e6a98d82edf8/pkgs/sources.toml

**Comment by Th3Whit3Wolf** [comment]
@nrdxp I'm glad you like the idea! I believe DevOS is the perfect place for this. Should I add this issue to digga?

**Comment by nrdxp** [comment]
@Th3Whit3Wolf , I'm more than happy to review a PR if you'd like to have a go at it

**Comment by Th3Whit3Wolf** [comment]
I will make some attempts but I am quite new to nix so I'm not sure I am entirely up for it.

**Comment by Th3Whit3Wolf** [comment]
@nrdxp I have made some progress! I have everything in [`pkgs/default.nix`](https://github.com/Th3Whit3Wolf/nixos/blob/devos/pkgs/default.nix) right now. With the move to nvfetcher I have changed my design.

`pkgs/default.nix` has 3 overlays. 

1. Allows sources to be used in `overlays`

```nix
overlaySrc = final: prev: {
  sources = (import ./_sources/generated.nix) { inherit (final) fetchurl fetchgit; };
};
```

2. Automatically and carefully callPackage for packages in `pkgs`

```nix
rakePkgs = dir: with builtins;
  let
    sieve = name: val:
      if isAttrs val then
        all (x: x == true)
        (forEach (attrNames val) (v:
          hasInfix "_sources" v
        ))
      else
        (val != ./default.nix && name != "bud");
  in
  mapAttrs' (name: value: 
    nameValuePair (last (splitString "." name)) (value)) (flattenTree (filterAttrs sieve (rakeLeaves dir)));

overlayLocal = final: prev: builtins.mapAttrs
  (name: value:
    let
      sources = (import ./_sources/generated.nix) { inherit (final) fetchurl fetchgit; };
      package = import (value);
      args = builtins.intersectAttrs (builtins.functionArgs package) { source = sources.${name}; };
    in
    final.callPackage package args
  ) (rakePkgs (./.));
```

* ignores `pkgs/_sources` and `pkgs/bud`
* `pkgs/manix` and `pkgs/misc/documentation/manix` both get create a pkg called `manix`
* instead of 
```nix
{ lib, stdenv, sources }:

stdenv.mkDerivation rec {
  inherit (sources.sanFranciscoMono-font) src pname version;
```

you do

```nix
{ lib, stdenv, sources }:

stdenv.mkDerivation rec {
  inherit (sources) src pname version;
```

3. Lastly an overlay for pkgSets (currently just vimPlugins). With the move to nvfetcher I think it makes sense to prefix pkgSets in nvfetcher and then build them.

For example in `pkgs/source.toml` I prefix pkgs apart of the vimPlugins package set with `VimPlugins-`. Then in the overlay we can collect them and strip the prefix when we build nixos. I am unsure if this will work for all package sets but I think it should work for a good portion of them, specifically text editors and programming language libraries.

```toml
[vimPlugins-ron-vim]
src.github = "ron-rs/ron.vim"
fetch.github = "ron-rs/ron.vim"
```

```nix
overlayPkgsSets = final: prev: {
  sources = (import ./_sources/generated.nix);
  vimPlugins = with final.vimUtils;
    let
      plugs = prev.lib.mapAttrs' (name: value: nameValuePair (prev.lib.removePrefix "vimPlugins-" name) (value)) (prev.lib.filterAttrs (n: v: prev.lib.hasPrefix "vimPlugins-" n) prev.sources);
      createVimPlugin = pname: version: src: prev.vimUtils.buildVimPluginFrom2Nix { inherit pname version src; };

      overridePkgVersionSrc = pkg: version: src: pkg.overrideAttrs (_: { inherit version src; });
      overrideOrCreateVimPlugin = plugin:
        let
          pname = prev.lib.removePrefix "vimPlugins-" plugin.pname;
          pkg = prev.vimPlugins.${pname} or { };
          version = plugin.version;
          src = plugin.src;
        in
          if pkg ? overrideAttrs then 
            overridePkgVersionSrc pkg version src
          else 
            createVimPlugin pname version src;

          mapVimPlugins = pluginsSet: prev.lib.mapAttrs'
            (name: src: prev.lib.nameValuePair name (overrideOrCreateVimPlugin pluginsSet.${name}))
            pluginsSet;
    in
    prev.vimPlugins // mapVimPlugins plugs;
  };
```

I also made a [nvfetcher feature request](https://github.com/berberman/nvfetcher/issues/14) to add vscode extensions. If anyone reading this is interested and more familiar with haskell I made a shell script (posted in [issue](https://github.com/berberman/nvfetcher/issues/14)), that uses curl and jq to get vscode extension versions and downloads, that might help get someone starteed.

**Comment by blaggacao** [comment]
I just saw the nvchecker PR was merged, do we have to wait for conformance?

**Comment by Th3Whit3Wolf** [comment]
@blaggacao yes and then we can throw vscode extension in `sources.toml`!

**Comment by Th3Whit3Wolf** [comment]
I added a function to make it easier to add pkgSets.

```nix
mapPkgSets = sources: pkgSet: pkgSetName: buildTool:
    let
      prefix = pkgSetName + "-";
      newPkgs = mapAttrs' (name: value: nameValuePair (removePrefix prefix name) (value)) (filterAttrs (n: v: hasPrefix prefix n) sources);
      createNewPkgs = pname: version: src: buildTool { inherit pname version src; };
      overridePkgVersionSrc = pkg: version: src: pkg.overrideAttrs (_: { inherit version src; });
      overrideOrCreatePkg = pkgFromSet:
        let
          pname = removePrefix prefix pkgFromSet.pname;
          pkg = pkgSet.${pname} or { };
          version = pkgFromSet.version;
          src = pkgFromSet.src;
        in
        if pkg ? overrideAttrs
        then overridePkgVersionSrc pkg version src
        else createNewPkgs pname version src;

      mapPackages = set: mapAttrs'
        (name: src: nameValuePair name (overrideOrCreatePkg set.${name}))
        set;
    in
    pkgSet // mapPackages newPkgs;
```

So that the pkgSets overlay can be created like this

```nix
  overlayPkgsSets = final: prev: {
    sources = (import ./_sources/generated.nix);

    vimPlugins = mapPkgSets prev.sources prev.vimPlugins "vimPlugins" prev.vimUtils.buildVimPluginFrom2Nix;
  };
```

It needs to be tested on more pkgSets. But I think it should work if anyone else is interested in trying it out my `pkgs/default.nix` [is here](https://github.com/Th3Whit3Wolf/nixos/blob/840eca6d436ba62e33035978bda586e89f95695f/pkgs/default.nix) and you would need to replace `./pkgs/default.nix` with `(import ./pkgs).overlay`.

@blaggacao and @nrdxp  I have checked out the digga source code and there's no way I can craft an importer, however the first 130 lines of the `pkgs/default.nix` are rakeLeaves, flattenTree, and functions from lib required to make them work so I think it may not be too difficult for someone with a bit more nix talent. I could make a PR here before it gets moved to digga if that would be preferable?

**Comment by Th3Whit3Wolf** [comment]
I've done some intense refactoring and I think I might be able to get a PR to digga this weekend.

**Comment by Th3Whit3Wolf** [comment]
Nevermind, I was way overly confident. I will send a PR to devos so people can get some eyes on the code.
