### ISSUE TITLE
How do I sync changes from master to my local setup?

### ISSUE THREAD

**Issue by cawilliamson** [divnix/digga#354]
This isn't really a bug report but there wasn't a "request help" type of label so had to go with this.

Short version is: I have devos setup nicely but I have no idea how to easily sync the changes made to this repo down to my local setup without wiping out my changes. Any help would be greatly appreciated!

Maybe I missed something in the docs about this and hopefully there's a helper for it.

Thanks!

**Comment by Pacman99** [comment]
Devos is a template for the usage of the digga library. So if you just want to update digga you can do `nix flake lock --update-input digga` but if you want to update the changes to devos you would have to use git.

So you need to add `divnix/devos` as a remote and pull the devos master/main branch and then `git merge <branch name>`. So for example:
```sh
git remote add upstream https://github.com/divnix/devos.git
git fetch upstream master
git merge upstream/master
```

This isn't necessarily recommended, but I usually just update digga as most feature changes are in there. I haven't updated devos itself in a long time. That does mean I'm currently missing the nvfetcher and bud integrations.

**Comment by Narice** [comment]
you can also do it manually by comparing the changes that were done between the commit you based your configuration on and the current one:
from v0.10 to today: https://github.com/divnix/devos/compare/f88acc1608ee719582fb19db34156d7c5d45a919...main

**Comment by montchr** [comment]
My ~fun~ approach to this:

- Download the ZIP archive of the current state of master
- Extract
- Drag the contents of the archive into my repo
- Revert any changes I don't want (very easy with magit)

I can't say I would recommend it, but it works. There's probably some smarter, quicker, easier approach using a git incantation to "pull" the upstream changes from this repo _without_ the history, but I have not yet discovered it.

**Comment by jared-w** [comment]
> I can't say I would recommend it, but it works. There's probably some smarter, quicker, easier approach using a git incantation to "pull" the upstream changes from this repo _without_ the history, but I have not yet discovered it.

Does

```sh
$ git remote add upstream git@github.com:divnix/devos.git
$ git fetch upstream
$ git diff v0.10.0 > upgrade.patch
$ git apply upgrade.patch
```

work? You'd still have a high likelihood of needing to apply any manual fixups, etc, from there

**Comment by pio2398** [comment]
I still think this is a problem, even more so than some time ago.
Some time ago, I could just do a rebase/merge on digga to my repo. It was fairly easy and quick. Because of moving the configuration to examples it is not so easy anymore.

**Comment by Pacman99** [comment]
Well I closed this because I no longer recommend trying to keep your repo in sync with the devos example. You can steal any new code for it manually. The majority of code updates have been in the digga library in the past few months. And digga can be updated just like any other flake inputs.
