### ISSUE TITLE
Updating/Rebuilding occasionally rebuilds way too many packages

### ISSUE THREAD

**Issue by cipharius** [divnix/digga#399]
I don't fully understand the update flow in devos, so not marking this as a bug as it's probably me misusing the system.

I'm confused about what is causing ~500 packages to be built during updates as I'm using nixpkgs release 21.05 channel for my base system and have picked only few packages from latest channel.

I suspect that the default `haskellPackages` override might be the cause of this overcompilation, by picking plenty of Haskell packages from latest channel. This came with the upstream configuration though, as I hadn't added it myself.

Here is my devos fork: https://github.com/cipharius/devos

**Comment by cipharius** [comment]
I disabled all latest channel overlays and that indeed greatly reduces count of packages to be compiled.

Doing some testing it seems that `cargo` from latest channel that I had just added was the main culprit. I'll try to look for cargo caches.

I'll leave this issue open for now as a prompt for better documentation on how devos updates and how it makes use of the NixOS channels. Whatever information I gathered was from exploring the `flake.nix` and `overlays/overrides.nix`, so it might be worth documenting.

**Comment by Pacman99** [comment]
Theres a chance that the groupByConfig example is running into this issue. For some reason even nix gets rebuilt during the check, even though the overlays applied are fairly simple.

**Comment by Pacman99** [comment]
Ahh I think the main issue is using `release-*` the flake input should be `nixos-*`. The former is a tag and not the branch

**Comment by cipharius** [comment]
Good catch! So far the most annoying part about using flake managed nixos was the very slow updates. Hopefully this will improve things.

**Comment by cipharius** [comment]
Looks like `release-X` tag vs `nixos-X` branch has confused others as well: https://github.com/NixOS/release-wiki/pull/13

Personally I had no clue about the difference and I hadn't seen any clear documentation on which branch/tag to base a system on.

**Comment by cipharius** [comment]
Alright, I found where in nixpkgs manual it mentions that `nixos-*` channels are what NixOS system should follow.

**Comment by Pacman99** [comment]
Yeah I misspoke, release-* is not a tag but a branch, its just where all the commits for the release are merged. The nixos-* branches reflect the state of tested commits by hydra, which means the packages in those commits have already been built.
