### ISSUE TITLE
add flk vm command

### ISSUE THREAD

**Issue by codygman** [divnix/digga#41]
I can't paste in the commands now, but following the manual from a clean OVA I had a few issues. Later I'll post out issues from each step.

## Your Environment
https://channels.nixos.org/nixos-20.09/latest-nixos-x86_64-linux.ova

**Comment by Narice** [comment]
I will try to take care of that with a PR that will also have probably a `run` subcommand to run the vm directly
Can someone confirm if it needs qemu support or if downloading it is part of the vm creation process?

**Comment by blaggacao** [comment]
Just additional info: https://github.com/NixOS/nixpkgs/blob/edb5ff75f24e95e1ff2a05329e4c051de5eea4f2/flake.nix#L58-L59

I think `vm` is enough, though, for the most part.

**Comment by Narice** [comment]
Should this issue be closed? It is now available on the develop branch of the project :wink:
