### ISSUE TITLE
PoetrySlam - What does the rakeLeaves function do?

### ISSUE THREAD

**Issue by MatthewCroughan** [divnix/digga#429]
https://github.com/divnix/devos/blob/main/flake.nix#L108

The documentation uses overloaded terms and flowery language. Can anyone explain to me what the point of this function is? 

https://github.com/divnix/devos/blob/a25d78b9c3d7fddd2c9345e2a38d858cd06bc9eb/doc/concepts/profiles.md#creation

**Comment by blaggacao** [comment]
It rakes leaves. That's the point.

"Leaves" as in leaves of a tree, defined by a folder structure.

**Comment by DarthPJB** [comment]
Your poetic skills impressed me so much, I felt the need to immortalise the 'flowery' wording, before I make like a tree - and split.

![image](https://user-images.githubusercontent.com/7378514/154859434-6fc4941d-03df-4e45-99b3-59a01d027d06.png)

**Comment by Pacman99** [comment]
Take a look at the function description here: https://github.com/divnix/digga/blob/33bfb05b8a148d8ad6a842de74e22209bf9fe5d7/src/importers.nix#L61. Its more technical on what exactly happens and gives an example.

**Comment by blaggacao** [comment]
@DarthPJB Great Parody! You afforded me a really good laugh! Thank you. :rofl:

**Comment by blaggacao** [comment]
@DarthPJB would you mind making anotherone for @nrdxp ? He's the actual author of the name `rakeLeaves`. And he wants one, too. :pray:

**Comment by DarthPJB** [comment]
![gimp-2 10_GajuU9jTPl](https://user-images.githubusercontent.com/7378514/155256868-e01f00df-2a6d-4b5c-83b8-2d42bef8a738.png)

It's only appropriate he be the emperor then!
@blaggacao @nrdxp

**Comment by ursi** [comment]
I take issue with this name. If we are raking leaves, does that not mean the leaves have fallen to the ground? In other words, raked leaves are leaves that no longer belonged to a tree, so the entire analogy falls apart. I suggest naming it something more clear, like `harvestTea`, as tea harvesting involves picking leaves that are *still attached* to a tree.

**Comment by blaggacao** [comment]
But as you see, the king would never drink tee, only wine. So we need more creative input, I guess :smile:

**Comment by MatthewCroughan** [comment]
https://readingmatrix.com/files/21-n15v144o.pdf

**Comment by blaggacao** [comment]
> University of Siirt
> This study investigated introduction and
conclusion parts of a hundred research articles written in English by Turkish speakers, and
picked up unnecessary complicated words, phrases and sentences.

I can imagine where this is coming form :rofl:

**Comment by pinktrink** [comment]
I mean removing leaves is indeed an act of pruning, `pruneTree`? `someGardening`?

**Comment by DarthPJB** [comment]
How about ```burnLeaves```

**Comment by blaggacao** [comment]
I think `explodeTree` would also be appropriate. Associative to the idiom "explode a bill of materials". :smile:

All this creativity is refreshing!

Keep the jam session rollin. :drumroll;

**Comment by nrdxp** [comment]
> It's only appropriate he be the emperor then!

Actually I'm kinda jealous of @blaggacao's hat :rofl: 

Also had someone at work suggest the slightly "dryer" `collectLeafNodes` :thinking:

**Comment by MatthewCroughan** [comment]
Thanks to this discussion, I have come to a more preponderant and more consummate understanding of what the purported utilization of the function is. I cerebrate this issue can now be closed!
