### ISSUE TITLE
Merge into digga

### ISSUE THREAD

**Issue by Pacman99** [divnix/digga#430]
Maintaining two separate repositories for such connected projects is becoming increasingly difficult. Anytime something changes in digga, an accompanying pull request has to be made in devos to fix the changes. We're maintaining two "separate" docs and projects when they really are the same thing.

I think this repo should just be a folder in the digga examples folder instead of being its own repo. The majority of issues in this repo are really about digga. Most of the "devos" docs are just about applications of the digga api.

Merging this repo into digga wouldn't change a whole lot. We can export the devos template with the `templates` output in digga, so all the getting started docs will still apply, but just with the digga api instead. `nix flake new -t github:divnix/digga`.

In terms of discoverability, we can move all the devos docs to be part of digga's docs and link the getting started in the digga readme.

cc @nrdxp @blaggacao

**Comment by blaggacao** [comment]
Perfect!

In order to.preserve github's ⭐, we might need to do a bit of a rochade:

- rename digga to something else

- merge digga into devos the way you propose

- rename devos to digga


---

This is really a simple, though geniouy idea on how to solve the maintenance issue.

**Comment by Pacman99** [comment]
Great idea! That way we can also preserve issues on devos too

**Comment by Pacman99** [comment]
Going to pin this issue, so people know what just happened

**Comment by Pacman99** [comment]
For contributors, its going to be awkward since this repository's forks are still devos. I think you can just delete your digga fork and rename your devos fork to digga then merge in main.

But if you have important branches in your digga fork, make sure to copy those over. Based off current pull requests in digga, this should mostly be a problem for @blaggacao @montchr and me.

**Comment by nrdxp** [comment]
for the record, I was against the split in the beginning :trollface:
