### ISSUE TITLE
Release v0.11.0

### ISSUE THREAD

**Issue by Pacman99** [divnix/digga#437]
I think we should continue off of devos's version numbers and tag a v0.11.0 release in this repo and talk about the project switch and rename to focus on digga.

cc @nrdxp @blaggacao @montchr

**Comment by blaggacao** [comment]
Wait for #436?

**Comment by Pacman99** [comment]
Yeah I think that should be the last code change to make it into the release. Maybe some docs cleanups could be included to.

**Comment by Pacman99** [comment]
Lets move forward with this, @montchr would you like to do the honors?
The latest commit just needs to be tagged `v0.11.0` and pushed to main, the release workflow should take care of the rest.
We can then edit the github changelog message to add more details

**Comment by montchr** [comment]
Will do! I'll get to it in the next couple hours.

**Comment by nrdxp** [comment]
Great job on another release guys! I had basically nothing to do with this one :sweat_smile: 

Excellent work :partying_face:
