### ISSUE TITLE
"Check & Cachix" workflow failing on `main`

### ISSUE THREAD

**Issue by montchr** [divnix/digga#443]
## Expected Behavior
The "Check & Cachix" workflow should pass on the `main` branch.

## Current Behavior
The "Check & Cachix" workflow is failing with the following error in `nix develop --command evalnix`:

```
error: flake 'git+file:///home/runner/work/digga/digga' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

## Possible Solution
5b33c4baefe44379b80592fbf531304ff3b513b7 appears to have introduced the change.

I'm not entirely sure what the preferred solution should be. But for the time being I would recommend reverting the commit that introduced the issues and submit it as a pull request, ensuring that builds pass before merging.

## Steps to Reproduce
https://github.com/divnix/digga/runs/5668623763?check_suite_focus=true

## Context
I'm unable to work on #438 since rebasing onto `main`.

**Comment by blaggacao** [comment]
fixed on `main` sorry for the oversight. dotfiles are the `rg` blind spot.
