### ISSUE TITLE
User disabled `useGlobalPkgs` conflicts with useGlobalPkgs set in `digga/src/modules.nix`

### ISSUE THREAD

**Issue by Narice** [divnix/digga#48]
I would like to seperate the packages that are for the os and the ones that are for the users.
to do that, I would like to have access to the nixpkgs.* options for home-manager that are disabled when useGlobalPkgs is set to true.
To be precise, I want to list the unfree packages for the os in the `flake.nix` of devos and the unfree packages of the user in its relevant user `default.nix` file.
This is better and has to my knowledge no drawbacks as the `nixpkgs` of the `home` input in devos follows the `nixos` input, as such, I think that the useGlobalPkgs in the following line should be turned off as with flakes there are to my knowlegde no drawbacks as the nixpkgs of the whole system is pinned to one source.
If there is a drawback that I am not aware off, would it be possible as a user to turn it off and could it be added in the documentation?
https://github.com/divnix/digga/blob/0cbc8bd4defee8fddc0c582556267bd2c1c02704/src/modules.nix#L7

**Comment by Pacman99** [comment]
I don't think `useGlobalPkgs = false` is a good default. It means that for each home-manager user you would have to set your nixpkgs config for every home-manager user and I believe that overlays won't get carried over.
In general because mkFlake has a `channels` argument, we want to ensure that the channel you pick gets sent everywhere to your host as `pkgs`.
Maybe we could just make it `useGlobalPkgs = lib.mkDefault true;` so that you can change it to false.

**Comment by Narice** [comment]
Ok, so it can be turned off right now using `lib.mkForce` (`profiles/core/default.nix`):
```nix
  home-manager = {
    useUserPackages = true;
    useGlobalPkgs = lib.mkForce false;
  };
```
However, you absolutely have to set the `home.stateVersion` to > `20.09` in your user profiles as the home-manager flake is too old and thus doesn't have this change:
https://github.com/nix-community/home-manager/blob/7591c8041d290d4bb99679e9fed2d8061a8f0435/flake.nix#L33-L35

yes! making it into a default would be better!
And I see the possible drawbacks, that is very interesting

**Comment by Narice** [comment]
After a short time thinking about it, your drawbacks are actually so huge that I decided to switch back to using the global pkgs.
Having the list of all unfree packages at one spot even has some advantages in case you want to go fully free at some point so that is actually fine, thank you very much for your comment which helped me a ton @Pacman99!

**Comment by Narice** [comment]
I will close this issue as there is a way to change the `useGlobalPkgs` option.
