### ISSUE TITLE
Integrate with nixos-generators

### ISSUE THREAD

**Issue by blaggacao** [divnix/digga#49]
We already have `flk iso|vm|doi`, but users want more. And we want to rely on the best available upstream aggregate for that task: [`nixos-generators`](https://github.com/nix-community/nixos-generators/pull/100) which shall become part of the [familiy](https://github.com/divnix/devos#family--like-family).

/cc @lassulus

**Comment by Lassulus** [comment]
whats doi?

**Comment by Pacman99** [comment]
doi is "Digitial Ocean Image" which will be soon switched to just `do` following the nixos-generators format name.

**Comment by blaggacao** [comment]
This is accomplished via https://github.com/divnix/digga/pull/50
