### ISSUE TITLE
reevaluation of `pkgs` for every mkDeployNodes

### ISSUE THREAD

**Issue by blaggacao** [divnix/digga#75]
https://github.com/divnix/digga/blob/7b0b6c5e424d6089d1f2f05ec8b7a0035677b7b5/src/generators.nix#L26

`appendOverlays` has the following warning in its code comment: (actually the `extend` wrapper has)

```
    # NOTE: each call to extend causes a full nixpkgs rebuild, adding ~130MB
    #       of allocations. DO NOT USE THIS IN NIXPKGS.
```

And that was added 2020 by zimbatm. it's probably a bit more by now.

Not sure how much memoization catches of this, but maybe it's generally safer to instantiate more globally deploy with nixpkgs, rather then nixpkgs with deploy.

**Comment by blaggacao** [comment]
#73 seems to break usage of `digga` with the fix enabled:


With follows fix:
```
nix flake update
warning: Git tree '/home/blaggacao/ghq/github.com/blaggacao/devos' is dirty
error: input 'digga/deploy/nixpkgs' follows a non-existent input 'digga/nixos'
```

Without the fix enabled, _no_ downstream user can pull in `deploy` anymore, see:

```
nix develop
warning: Git tree '/home/blaggacao/ghq/github.com/blaggacao/devos' is dirty
error: input 'deploy/naersk/nixpkgs' follows a non-existent input 'nixpkgs
```

**Comment by blaggacao** [comment]
Since this is hard-blocking me and there is no way out, I'll have to revert #73 until a better solutions can be found.

**Comment by Pacman99** [comment]
I don't think a reevaluation is such a big issue. At the very least I think its a worthy sacrifice to making digga nixpkgs free.

**Comment by blaggacao** [comment]
>I don't think a reevaluation is such a big issue.

We'd analyze at least how it scales with more than one host. If it effectively reevaluates, then this is a show stopper if each host penalizes with 130 MB RAM just for using deploy.

**Comment by blaggacao** [comment]
Temporarily closed by https://github.com/divnix/digga/commit/adee82d42dfcf6c34ccc8a2303116b17750bf522
