### ISSUE TITLE
`mkFlake` assumes valid values for `nixos.hostDefaults.channelName`

### ISSUE THREAD

**Issue by blaggacao** [divnix/digga#76]
[`mkFlake` requires `nixos.hostDefaults.channelName` to be set](https://github.com/divnix/digga/blob/adee82d42dfcf6c34ccc8a2303116b17750bf522/src/mkFlake/default.nix#L99) to a meaningful value. But that is not enforced (`default = null;`)

**Comment by Pacman99** [comment]
closed by #77
