### ISSUE TITLE
nix config is overriding

### ISSUE THREAD

**Issue by blaggacao** [divnix/digga#91]
https://github.com/divnix/digga/blob/f25928ed0bf05ab20af5a8231d264ae01b42ab34/modules/nix-config.nix#L23-L26

does not behave well with the current implementation of this option, since later values seem to override previous values: https://github.com/NixOS/nixpkgs/blob/b2f87e0043aaf3f0f05cc983bd6aa80a616b8352/nixos/modules/services/misc/nix-daemon.nix#L59

**Comment by nrdxp** [comment]
this should have been fixed in #93, but apparently GitHub didn't recognize the two as linked. Closing now.
